services:

  nginx:
    image: nginx:1.24.0-alpine
    ports:
      - 80:80
    volumes:
      - ./app:/usr/share/nginx/html
      - ./config/nginx/conf.d:/etc/nginx/conf.d

  php:
    image: php:8.1-fpm-alpine
    volumes:
      - ./app:/usr/share/nginx/html
    build:
      context: ./config/php
      dockerfile: php.Dockerfile

  mysql:
    image: mysql
    ports:
      - 3306:3306
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: my_db_test
      MYSQL_ALLOW_EMPTY_PASSWORD: yes

  myadmin:
    image: phpmyadmin
    ports: 
      - 8001:80
    environment:
      - PMA_HOST=mysql
      - PMA_PORT=3306
      - MEMORY_LIMIT=712M
      - UPLOAD_LIMIT=712M
